### ISSUE TITLE
Camera doesn't work!!

### ISSUE THREAD

**Issue by offset1313** [nE0sIghT/android_kernel_xiaomi_msm8953#19]
Here is dmesg with 3.18 camera stack:

https://gist.github.com/offset1313/5b2381ead4d9a3db4d5580b32e269790

Here is dmesg with 4.9 camera stack:

https://gist.github.com/offset1313/66d9b3fadabef192c1b4ed90587ca203

**Comment by nE0sIghT** [comment]
> Here is dmesg with 3.18 camera stack:

It is 4.9.220-perf

**Comment by Nicklas373** [comment]
> > Here is dmesg with 3.18 camera stack:
> 
> It is 4.9.220-perf

yes, i was checkout to 3.18 camera_v2 drivers on the kernel

**Comment by offset1313** [comment]
**_Captured on same ROM :_**

working camera:
https://gist.github.com/offset1313/9beb763b984d404488755d9f7839e456#file-3-18-140

Camera not working:
https://gist.github.com/offset1313/7a2c129f994644f65fd4d30c4ccde081#file-4-9-188

**Comment by Nicklas373** [comment]
Captured on lineage 17.1 from aryan using 4.9 kernel with 3.18 camera stack

logcat:
https://gist.github.com/Nicklas373/1a46020b8db0c2dcaf23c6027556af58

kmsg:
https://gist.github.com/Nicklas373/13216376e471d93e014436bb9aa8016d

I notice there's similiar error with failed to read eeprom on 3.18 kernel and 4.9 kernel with 3.18 camera stack.

**Comment by offset1313** [comment]
Logcat from working camera on 3.18.140 kernel:

https://gist.github.com/offset1313/d72a89c7e9780770b962d7b7c83a5469#file-logcat
