### ISSUE TITLE
Kernel panic on shutdown

### ISSUE THREAD

**Issue by nE0sIghT** [nE0sIghT/android_kernel_xiaomi_msm8953#21]
Using Android reboot menu. Adb reboot works as expected.

**Comment by 3EleVen** [comment]
see this commit   https://github.com/MoKee/android_kernel_xiaomi_onclite/commit/8cb9c278979240ff1a0f3a8ee276d17575d62e76#diff-567adfad6cf693a5d6f76e3dbc929db1

**Comment by nE0sIghT** [comment]
Did you tested it?

**Comment by 3EleVen** [comment]
> Did you tested it?

no. you can try it.

**Comment by nE0sIghT** [comment]
https://gist.github.com/nE0sIghT/36d6d3a4e9d8194ec883b641c2f2e6b8

**Comment by nE0sIghT** [comment]
Shutdown with ipa debug: https://gist.github.com/nE0sIghT/e08ffa2ad26989faa28c9fe09dec7319

**Comment by nE0sIghT** [comment]
I reworked lineage-16.0 branch on top of latest mainline/caf/aosp kernels and there is no such issue anymore.
