### ISSUE TITLE
Clang 11 compilation fixed

### ISSUE THREAD

**Issue by offset1313** [nE0sIghT/android_kernel_xiaomi_msm8953#6]
When compiling with clang 11 few error were generated leading to compilation failure:
All those have been fixed in :
https://github.com/offset1313/Mido_Revived/commit/5214b0f9eeede6933e207deb3f1149709e4714be

https://github.com/offset1313/Mido_Revived/commit/00b806d746e390571fd62188b0c78f82ec46ef74

https://github.com/offset1313/Mido_Revived/commit/472dfa0afbcdd3cfb51e72c4f03d64ce25a53526
Sharing just for reference

While third commit just fixes a 2nd commit accidental lefover

**Comment by Nicklas373** [comment]
All hovercard link can't be open, anyway clang 11 doesn't have any issue here. Test with proton clang 11  with compat vdso

**Comment by offset1313** [comment]
I just deleted than repo sorry but there were problems in compilation with clang 11 when you use this source you are using your own source based on 4.9.206 not source in this repo  and already have fixes there

**Comment by Nicklas373** [comment]
Whoops yes, forget to check that. Yes, latest revision of upstream already patched for that...

**Comment by offset1313** [comment]
Dunno if fixes are upstream or you have cherry-picked

**Comment by Nicklas373** [comment]
I pick from that tag, tbh, that aren't latest tag too
